spring.application.name=DC_Backend_Services

# sql config
spring.datasource.url=jdbc:mysql://rm-wz9i53y03487e63x3wo.mysql.rds.aliyuncs.com:3306/da_chaung_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
spring.datasource.username=test_1
spring.datasource.password=!Dc12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# jpa config
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=9090

# ai config
volcengine.ark.api-key =${ARK_API_KEY_T01}

spring.jackson.deserialization.fail-on-unknown-properties=false